version: '3.1'

services:
  currency_service:
    build:
      context: .
    container_name: currency_service
    restart: always
    ports:
      - "8091:8090"
#    env_file:
#      - ../../local.env
